import {
  School,
  SchoolClass,
  Student,
  ParentStudentRelation,
  Announcement,
  AttendanceRecord,
  AppNotification,
  SaaSPlan,
  User,
  AcademicYear,
} from './types';

export const INITIAL_SCHOOLS: School[] = [
  {
    id: 'school-1',
    name: 'Groupe Scolaire Horizon Wend-Manegda',
    city: 'Ouagadougou (Secteur 28)',
    country: 'Burkina Faso',
    address: 'Avenue de la Liberté, Secteur 28, Ouagadougou',
    phone: '+226 25 36 00 12',
    email: 'direction@horizon-ouaga.bf',
    plan: 'main',
    monthlyFee: 10000,
    classesCount: 8,
    studentsCount: 320,
    parentsCount: 285,
    code: 'GS-HORIZON',
    status: 'active',
  },
  {
    id: 'school-2',
    name: 'Complexe Éducatif Les Étoiles du Faso',
    city: 'Bobo-Dioulasso (Bindougousso)',
    country: 'Burkina Faso',
    address: 'Rue 14.120, Bobo-Dioulasso',
    phone: '+226 20 97 14 55',
    email: 'contact@lesetoiles-bobo.bf',
    plan: 'free',
    monthlyFee: 0,
    classesCount: 3,
    studentsCount: 95,
    parentsCount: 88,
    code: 'CE-ETOILES',
    status: 'trial',
  },
  {
    id: 'school-3',
    name: 'Collège Privé Sainte-Monique',
    city: 'Koudougou',
    country: 'Burkina Faso',
    address: 'Quartier Burkina, Koudougou',
    phone: '+226 25 44 02 88',
    email: 'admin@stemonique-bf.org',
    plan: 'advanced',
    monthlyFee: 25000,
    classesCount: 14,
    studentsCount: 560,
    parentsCount: 510,
    code: 'COL-STEMONIQUE',
    status: 'active',
  },
];

export const INITIAL_ACADEMIC_YEARS: AcademicYear[] = [
  {
    id: 'year-2024-2025',
    schoolId: 'school-1',
    name: '2024-2025',
    startDate: '2024-10-01',
    endDate: '2025-06-30',
    status: 'closed',
    isDefault: false,
  },
  {
    id: 'year-2025-2026',
    schoolId: 'school-1',
    name: '2025-2026',
    startDate: '2025-10-01',
    endDate: '2026-06-30',
    status: 'active',
    isDefault: true,
  },
  {
    id: 'year-2026-2027',
    schoolId: 'school-1',
    name: '2026-2027',
    startDate: '2026-10-01',
    endDate: '2027-06-30',
    status: 'upcoming',
    isDefault: false,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-director-1',
    name: 'M. Salif Ouédraogo',
    email: 'directeur@horizon-ouaga.bf',
    phone: '+226 70 21 34 56',
    role: 'director',
    schoolId: 'school-1',
    title: 'Directeur Général des Études',
    status: 'active',
    lastLogin: '2026-09-24T08:15:00Z',
  },
  {
    id: 'user-teacher-1',
    name: 'Mme Fatou Traoré',
    email: 'f.traore@horizon-ouaga.bf',
    phone: '+226 76 55 43 21',
    role: 'teacher',
    schoolId: 'school-1',
    title: 'Professeure Principale — CM2 A',
    status: 'active',
    assignedClassIds: ['class-cm2a'],
    lastLogin: '2026-09-24T07:45:00Z',
  },
  {
    id: 'user-teacher-2',
    name: 'M. Ibrahim Kinda',
    email: 'i.kinda@horizon-ouaga.bf',
    phone: '+226 71 22 33 44',
    role: 'teacher',
    schoolId: 'school-1',
    title: 'Enseignant Titulaire — CM1 B',
    status: 'active',
    assignedClassIds: ['class-cm1b'],
    lastLogin: '2026-09-23T14:30:00Z',
  },
  {
    id: 'user-teacher-3',
    name: 'M. Paul Sanou',
    email: 'p.sanou@horizon-ouaga.bf',
    phone: '+226 78 12 34 56',
    role: 'teacher',
    schoolId: 'school-1',
    title: 'Professeur de Français — 6ème Bleue',
    status: 'active',
    assignedClassIds: ['class-6eme'],
    lastLogin: '2026-09-24T08:00:00Z',
  },
  {
    id: 'user-parent-1',
    name: 'M. Ousmane Sawadogo',
    email: 'ousmane.sawadogo@gmail.com',
    phone: '+226 78 90 12 34',
    role: 'parent',
    schoolId: 'school-1',
    title: 'Parent d\'élève (2 enfants scolarisés)',
    status: 'active',
    lastLogin: '2026-09-24T08:20:00Z',
  },
  {
    id: 'user-parent-2',
    name: 'Mme Kadidiatou Bado',
    email: 'k.bado@gmail.com',
    phone: '+226 78 33 44 55',
    role: 'parent',
    schoolId: 'school-1',
    title: 'Parent d\'élève',
    status: 'active',
    lastLogin: '2026-09-23T11:40:00Z',
  },
  {
    id: 'user-secretary-1',
    name: 'Mme Mariam Kaboré',
    email: 'secretariat@horizon-ouaga.bf',
    phone: '+226 71 88 99 00',
    role: 'secretary',
    schoolId: 'school-1',
    title: 'Secrétaire de Direction & Scolarité',
    status: 'active',
    lastLogin: '2026-09-24T08:05:00Z',
  },
  {
    id: 'user-superadmin-1',
    name: 'Équipe SaaS Stratège',
    email: 'support@ecoleconnect.africa',
    phone: '+226 75 00 11 22',
    role: 'super_admin',
    schoolId: 'all',
    title: 'Super Administrateur Plateforme',
    status: 'active',
    lastLogin: '2026-09-24T08:30:00Z',
  },
];

export const INITIAL_CLASSES: SchoolClass[] = [
  {
    id: 'class-cp1',
    schoolId: 'school-1',
    academicYearId: 'year-2025-2026',
    name: 'CP1 A (Initiation)',
    gradeLevel: 'CP1',
    division: 'A',
    teacherId: 'user-teacher-2',
    teacherName: 'M. Ibrahim Kinda',
    studentsCount: 30,
    room: 'Bâtiment A - Salle 01',
  },
  {
    id: 'class-ce2',
    schoolId: 'school-1',
    academicYearId: 'year-2025-2026',
    name: 'CE2 Harmonie',
    gradeLevel: 'CE2',
    division: 'Harmonie',
    teacherId: 'user-teacher-2',
    teacherName: 'M. Ibrahim Kinda',
    studentsCount: 34,
    room: 'Bâtiment A - Salle 02',
  },
  {
    id: 'class-cm1b',
    schoolId: 'school-1',
    academicYearId: 'year-2025-2026',
    name: 'CM1 B',
    gradeLevel: 'CM1',
    division: 'B',
    teacherId: 'user-teacher-2',
    teacherName: 'M. Ibrahim Kinda',
    studentsCount: 35,
    room: 'Bâtiment B - Salle 03',
  },
  {
    id: 'class-cm2a',
    schoolId: 'school-1',
    academicYearId: 'year-2025-2026',
    name: 'CM2 A (Examen CEP)',
    gradeLevel: 'CM2',
    division: 'A',
    teacherId: 'user-teacher-1',
    teacherName: 'Mme Fatou Traoré',
    studentsCount: 38,
    room: 'Bâtiment B - Salle 04',
  },
  {
    id: 'class-6eme',
    schoolId: 'school-1',
    academicYearId: 'year-2025-2026',
    name: '6ème Bleue (Collège)',
    gradeLevel: '6e',
    division: 'Bleue',
    teacherId: 'user-teacher-3',
    teacherName: 'M. Paul Sanou',
    studentsCount: 42,
    room: 'Bâtiment Secondaire - Salle 12',
  },
  {
    id: 'class-3eme',
    schoolId: 'school-1',
    academicYearId: 'year-2025-2026',
    name: '3ème A (Examen BEPC)',
    gradeLevel: '3e',
    division: 'A',
    teacherId: 'user-teacher-3',
    teacherName: 'M. Paul Sanou',
    studentsCount: 40,
    room: 'Bâtiment Secondaire - Salle 15',
  },
  {
    id: 'class-tle-d',
    schoolId: 'school-1',
    academicYearId: 'year-2025-2026',
    name: 'Terminale D (Scientifique)',
    gradeLevel: 'Tle',
    division: 'D',
    teacherId: 'user-teacher-3',
    teacherName: 'M. Paul Sanou',
    studentsCount: 35,
    room: 'Bâtiment Secondaire - Salle 21',
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'stud-1',
    schoolId: 'school-1',
    academicYearId: 'year-2025-2026',
    classId: 'class-cm2a',
    className: 'CM2 A (Examen CEP)',
    matricule: 'HORIZ-2026-088',
    firstName: 'Aminata',
    lastName: 'Sawadogo',
    gender: 'F',
    birthDate: '2015-04-12',
    verificationCode: 'LINK-8841',
    guardianPhone: '+226 78 90 12 34',
    guardianName: 'M. Ousmane Sawadogo',
    status: 'enrolled',
  },
  {
    id: 'stud-2',
    schoolId: 'school-1',
    academicYearId: 'year-2025-2026',
    classId: 'class-ce2',
    className: 'CE2 Harmonie',
    matricule: 'HORIZ-2026-142',
    firstName: 'Ibrahim',
    lastName: 'Sawadogo',
    gender: 'M',
    birthDate: '2017-09-25',
    verificationCode: 'LINK-3392',
    guardianPhone: '+226 78 90 12 34',
    guardianName: 'M. Ousmane Sawadogo',
    status: 'enrolled',
  },
  {
    id: 'stud-3',
    schoolId: 'school-1',
    academicYearId: 'year-2025-2026',
    classId: 'class-cm2a',
    className: 'CM2 A (Examen CEP)',
    matricule: 'HORIZ-2026-015',
    firstName: 'Cheick',
    lastName: 'Ouédraogo',
    gender: 'M',
    birthDate: '2015-01-18',
    verificationCode: 'LINK-7720',
    guardianPhone: '+226 70 44 55 66',
    guardianName: 'M. Moussa Ouédraogo',
    status: 'enrolled',
  },
  {
    id: 'stud-4',
    schoolId: 'school-1',
    academicYearId: 'year-2025-2026',
    classId: 'class-cm2a',
    className: 'CM2 A (Examen CEP)',
    matricule: 'HORIZ-2026-064',
    firstName: 'Alimata',
    lastName: 'Kaboré',
    gender: 'F',
    birthDate: '2015-06-30',
    verificationCode: 'LINK-5519',
    guardianPhone: '+226 76 11 22 33',
    guardianName: 'Mme Fatimata Kaboré',
    status: 'enrolled',
  },
  {
    id: 'stud-5',
    schoolId: 'school-1',
    academicYearId: 'year-2025-2026',
    classId: 'class-cm2a',
    className: 'CM2 A (Examen CEP)',
    matricule: 'HORIZ-2026-099',
    firstName: 'Romaric',
    lastName: 'Bado',
    gender: 'M',
    birthDate: '2015-11-04',
    verificationCode: 'LINK-4481',
    guardianPhone: '+226 78 33 44 55',
    guardianName: 'Mme Kadidiatou Bado',
    status: 'enrolled',
  },
  {
    id: 'stud-6',
    schoolId: 'school-1',
    academicYearId: 'year-2025-2026',
    classId: 'class-6eme',
    className: '6ème Bleue (Collège)',
    matricule: 'HORIZ-2026-103',
    firstName: 'Nafissatou',
    lastName: 'Diallo',
    gender: 'F',
    birthDate: '2014-03-22',
    verificationCode: 'LINK-9932',
    guardianPhone: '+226 75 88 77 66',
    guardianName: 'M. Amadou Diallo',
    status: 'enrolled',
  },
];

export const INITIAL_RELATIONS: ParentStudentRelation[] = [
  {
    id: 'rel-1',
    parentId: 'user-parent-1',
    parentName: 'M. Ousmane Sawadogo',
    parentPhone: '+226 78 90 12 34',
    studentId: 'stud-1',
    studentName: 'Aminata Sawadogo',
    studentMatricule: 'HORIZ-2026-088',
    className: 'CM2 A (Examen CEP)',
    relationType: 'Père',
    status: 'approved',
    requestedAt: '2026-09-10T08:30:00Z',
    approvedAt: '2026-09-10T10:15:00Z',
  },
  {
    id: 'rel-2',
    parentId: 'user-parent-1',
    parentName: 'M. Ousmane Sawadogo',
    parentPhone: '+226 78 90 12 34',
    studentId: 'stud-2',
    studentName: 'Ibrahim Sawadogo',
    studentMatricule: 'HORIZ-2026-142',
    className: 'CE2 Harmonie',
    relationType: 'Père',
    status: 'approved',
    requestedAt: '2026-09-12T14:20:00Z',
    approvedAt: '2026-09-12T16:00:00Z',
  },
  {
    id: 'rel-3',
    parentId: 'user-parent-2',
    parentName: 'Mme Kadidiatou Bado',
    parentPhone: '+226 78 33 44 55',
    studentId: 'stud-5',
    studentName: 'Romaric Bado',
    studentMatricule: 'HORIZ-2026-099',
    className: 'CM2 A (Examen CEP)',
    relationType: 'Mère',
    status: 'pending',
    requestedAt: '2026-09-23T11:45:00Z',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    schoolId: 'school-1',
    targetType: 'all',
    authorId: 'user-director-1',
    authorName: 'M. Salif Ouédraogo',
    authorRole: 'Direction',
    title: 'Assemblée Générale des Parents d\'Élèves (Rentrée 2026-2027)',
    content:
      'Chers parents d\'élèves,\n\nLa Direction et le bureau APE ont le plaisir de vous convier à l\'Assemblée Générale annuelle qui se tiendra ce samedi à 09h00 précises dans la cour d\'honneur de l\'établissement.\n\nOrdre du jour :\n1. Bilan académique de l\'année écoulée et objectifs CEP/BEPC.\n2. Présentation du protocole de communication via la plateforme ÉcoleConnect.\n3. Projets d\'aménagements et questions diverses.\n\nVotre présence massive est vivement souhaitée pour le rayonnement de notre école.',
    smsVersion:
      '[GS HORIZON] AG des parents ce Samedi à 09h00 dans la cour d\'honneur. Présentation du bilan & plateforme. Présence vivement souhaitée.',
    priority: 'urgent',
    category: 'event',
    createdAt: '2026-09-22T07:30:00Z',
    readCount: 242,
    totalTargets: 285,
    readByCurrentParent: true,
  },
  {
    id: 'ann-2',
    schoolId: 'school-1',
    targetType: 'class',
    targetClassId: 'class-cm2a',
    targetClassName: 'CM2 A (Examen CEP)',
    authorId: 'user-teacher-1',
    authorName: 'Mme Fatou Traoré',
    authorRole: 'Enseignant',
    title: 'Devoir surveillé d\'Histoire-Géographie & Sciences — Vendredi',
    content:
      'Bonjour chers parents,\n\nNous aurons une évaluation sommative ce vendredi 26 septembre sur :\n- Histoire : La Haute-Volta et les chefferies traditionnelles.\n- Sciences : La digestion et la respiration humaine (Leçons 1 à 4).\n\nPrière de veiller à ce que les enfants révisent bien leurs cahiers de leçons ce soir et jeudi soir.',
    smsVersion:
      '[CM2 A] Devoir Histoire & Sciences ce Vendredi 26/09. Merci de vérifier la révision des leçons 1 à 4.',
    priority: 'important',
    category: 'pedagogy',
    createdAt: '2026-09-23T15:10:00Z',
    readCount: 31,
    totalTargets: 38,
    readByCurrentParent: false,
  },
  {
    id: 'ann-3',
    schoolId: 'school-1',
    targetType: 'all',
    authorId: 'user-secretary-1',
    authorName: 'Mme Mariam Kaboré',
    authorRole: 'Secrétariat',
    title: 'Visite médicale scolaire annuelle — Carnets de santé exigés',
    content:
      'Chères familles,\n\nL\'équipe médicale du district sanitaire effectuera le contrôle annuel de santé (vue, carnet de vaccination, pesée) du mardi 30 septembre au jeudi 2 octobre.\n\nMerci de glisser le carnet de santé de votre enfant dans son sac.',
    smsVersion:
      '[GS HORIZON] Contrôle médical annuel dès mardi 30/09. Carnet de santé obligatoire dans le sac de l\'élève.',
    priority: 'normal',
    category: 'general',
    createdAt: '2026-09-21T09:00:00Z',
    readCount: 198,
    totalTargets: 285,
    readByCurrentParent: true,
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    schoolId: 'school-1',
    classId: 'class-cm2a',
    className: 'CM2 A (Examen CEP)',
    studentId: 'stud-3',
    studentName: 'Cheick Ouédraogo',
    date: '2026-09-24',
    session: 'Matin',
    status: 'absent',
    reason: 'Absence non justifiée à l\'appel de 07h30',
    isJustified: false,
    justificationStatus: 'none',
    recordedBy: 'Mme Fatou Traoré',
    notifiedParents: true,
    createdAt: '2026-09-24T07:40:00Z',
  },
  {
    id: 'att-2',
    schoolId: 'school-1',
    classId: 'class-cm2a',
    className: 'CM2 A (Examen CEP)',
    studentId: 'stud-1',
    studentName: 'Aminata Sawadogo',
    date: '2026-09-22',
    session: 'Après-midi',
    status: 'late',
    durationMinutes: 15,
    reason: 'Embouteillage échangeur de l\'Est',
    isJustified: true,
    justificationStatus: 'accepted',
    justificationReason: 'Retard communiqué par téléphone par le père M. Sawadogo',
    recordedBy: 'Mme Fatou Traoré',
    notifiedParents: true,
    createdAt: '2026-09-22T14:45:00Z',
  },
  {
    id: 'att-3',
    schoolId: 'school-1',
    classId: 'class-cm2a',
    className: 'CM2 A (Examen CEP)',
    studentId: 'stud-5',
    studentName: 'Romaric Bado',
    date: '2026-09-23',
    session: 'Matin',
    status: 'absent',
    reason: 'Fièvre & Crise de paludisme',
    isJustified: true,
    justificationStatus: 'accepted',
    justificationReason: 'Certificat médical CSPS Secteur 28',
    recordedBy: 'Mme Fatou Traoré',
    notifiedParents: true,
    createdAt: '2026-09-23T07:35:00Z',
  },
  {
    id: 'att-4',
    schoolId: 'school-1',
    classId: 'class-ce2',
    className: 'CE2 Harmonie',
    studentId: 'stud-2',
    studentName: 'Ibrahim Sawadogo',
    date: '2026-09-18',
    session: 'Matin',
    status: 'late',
    durationMinutes: 20,
    reason: 'Rendez-vous dentaire',
    isJustified: true,
    justificationStatus: 'accepted',
    recordedBy: 'M. Ibrahim Kinda',
    notifiedParents: true,
    createdAt: '2026-09-18T08:10:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    userId: 'user-parent-1',
    title: 'Nouvelle annonce de classe : Devoir CM2 A',
    message: 'Mme Traoré a publié le programme du devoir surveillé de Vendredi.',
    type: 'announcement',
    channel: 'in_app',
    isRead: false,
    createdAt: '2026-09-23T15:12:00Z',
    studentName: 'Aminata Sawadogo',
  },
  {
    id: 'notif-2',
    userId: 'user-parent-1',
    title: 'Retard enregistré pour Aminata (15 min)',
    message: 'Votre enfant est arrivée à 14h45 ce mardi. Motif : Embouteillage.',
    type: 'absence',
    channel: 'sms',
    isRead: true,
    createdAt: '2026-09-22T14:46:00Z',
    studentName: 'Aminata Sawadogo',
  },
  {
    id: 'notif-3',
    userId: 'user-parent-1',
    title: 'Liaison parent-enfant validée',
    message: 'La direction a validé votre accès au dossier d\'Ibrahim Sawadogo (CE2).',
    type: 'link_approved',
    channel: 'in_app',
    isRead: true,
    createdAt: '2026-09-12T16:01:00Z',
    studentName: 'Ibrahim Sawadogo',
  },
];

export const SAAS_PLANS: SaaSPlan[] = [
  {
    id: 'free',
    name: 'Offre Découverte',
    price: 0,
    currency: 'FCFA',
    billingPeriod: 'Gratuit à vie',
    subtitle: 'Pour tester le produit avec une petite école pilote.',
    classesLimit: 'Jusqu\'à 3 classes',
    features: [
      '1 établissement scolaire',
      '3 classes maximum incluses',
      'Annonces & notifications in-app illimitées',
      'Pointage absences par les enseignants',
      'Accès parents smartphone & web',
      'Historique sur 30 jours glissants',
    ],
  },
  {
    id: 'main',
    name: 'Offre Principale',
    price: 10000,
    currency: 'FCFA',
    billingPeriod: 'par mois',
    subtitle: 'Idéal pour écoles primaires et collèges privés en pleine croissance.',
    classesLimit: 'Jusqu\'à 15 classes',
    isPopular: true,
    badgeText: 'Le plus recommandé',
    features: [
      'Toutes les classes de l\'établissement',
      'Comptes enseignants & secrétariat illimités',
      'Annonces avec accusé de lecture par parent',
      'Suivi des absences & retards avec alertes instantanées',
      'Validation sécurisée des liaisons parents-enfants',
      'Génération d\'annonces avec Assistant IA',
      'Exportation des registres & assistance standard prioritaire',
    ],
  },
  {
    id: 'advanced',
    name: 'Offre Avancée',
    price: 25000,
    currency: 'FCFA',
    billingPeriod: 'par mois',
    subtitle: 'Pour les complexes scolaires d\'envergure et réseaux multi-sites.',
    classesLimit: 'Classes illimitées',
    badgeText: 'Multi-sites & Grands groupes',
    features: [
      'Nombre de classes & élèves illimités',
      'Support multi-sites ou extensions d\'établissement',
      'Rapports statistiques d\'assiduité et d\'engagement APE',
      'Canal passerelle SMS / WhatsApp d\'urgence',
      'Journal d\'audit complet des communications',
      'Accompagnement & formation dédiée des enseignants',
      'Sauvegarde quotidienne redondante & export ministériel',
    ],
  },
];
